name: Modular Crypto Analysis Platform with AI
on:
  schedule:
    - cron: '0 8 * * *'  # Täglich um 8:00 UTC (9:00 MEZ)
  workflow_dispatch:      # Manueller Start über GitHub UI

jobs:
  run-analysis:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Verify modular architecture
      run: |
        echo "🔍 Verifying modular architecture..."
        python -c "from config import API_CONFIG; print('✅ config.py loaded successfully')"
        python -c "from modules.utils.logger import logger; print('✅ logger module loaded successfully')"
        python -c "from modules.data_models import CoinAnalysisResult; print('✅ data_models loaded successfully')"
        echo "✅ All modules verified successfully!"
        
    - name: Run Modular Crypto Analysis Platform
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        BITVAVO_API_KEY: ${{ secrets.BITVAVO_API_KEY }}
        BITVAVO_API_SECRET: ${{ secrets.BITVAVO_API_SECRET }}
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: |
        echo "🚀 Starting modular crypto analysis platform..."
        python Test_script.py
        echo "✅ Analysis completed successfully!"
        
    - name: Upload Health Check
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: health-check
        path: health.json
        retention-days: 7
        
    - name: Upload Logs
      if: always()
      uses: actions/upload-artifact@v4  
      with:
        name: analysis-logs
        path: logs/
        retention-days: 7
