# Name des Workflows
name: Daily Crypto Analysis

# Trigger: Wann soll der Workflow laufen?
on:
  schedule:
    # Führt den Job jeden Tag um 08:00 UTC aus (10:00 deutsche Sommerzeit)
    - cron: '0 8 * * *'
  # Ermöglicht auch manuelles Starten für Tests
  workflow_dispatch:

# Jobs, die ausgeführt werden sollen
jobs:
  run-analysis:
    # Nutzt einen Standard-Server von GitHub
    runs-on: ubuntu-latest

    steps:
    # Schritt 1: Code aus dem Repository herunterladen
    - name: Check out repository code
      uses: actions/checkout@v4

    # Schritt 2: Python-Umgebung einrichten
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # Schritt 3: Notwendige Bibliotheken installieren
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ccxt pandas TA-Lib

    # Schritt 4: Das Analyse-Skript ausführen
    - name: Run Python script
      run: python Test_script.py

# ... (der obere Teil der Datei bleibt gleich) ...

    # Schritt 4: Das Analyse-Skript ausführen
    - name: Run Python script
      env:
        ALPHA_VANTAGE_API_KEY: ${{ secrets.ALPHA_VANTAGE_API_KEY }}
      run: python Test_script.py
