name: Daily Crypto Analysis

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  run-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # KORRIGIERT: Installiert jetzt "requests" statt "ccxt"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas TA-Lib

    # HINZUGEFÜGT: Dieser Block übergibt den API-Schlüssel sicher an das Skript
    - name: Run Python script
      env:
        ALPHA_VANTAGE_API_KEY: ${{ secrets.ALPHA_VANTAGE_API_KEY }}
      run: python Test_script.py
